# Generated by Django 3.0.4 on 2020-05-11 01:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('friends', models.ManyToManyField(blank=True, related_name='_userprofile_friends_+', to='APIlend.UserProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DebtMonetary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('isActive', models.BooleanField(default=True)),
                ('creditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditorMon', to='APIlend.UserProfile')),
                ('debtor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debtorMon', to='APIlend.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='DebtItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField(default=datetime.date.today)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('info', models.CharField(max_length=280)),
                ('image', models.ImageField(blank=True, upload_to='pics')),
                ('isActive', models.BooleanField(default=True)),
                ('creditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditorItem', to='APIlend.UserProfile')),
                ('debtor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debtorItem', to='APIlend.UserProfile')),
            ],
        ),
    ]
